In [1]:
import numpy as np

a = np.random.randn(3, 3)
b = np.random.randn(3, 1)

In [2]:
c = a*b 

In [3]:
print(c)

[[-0.8231658  -0.14221081  1.03433774]
 [ 1.83850522  0.70758546 -1.06450143]
 [-0.5706735   0.1787155   0.23021924]]


In [4]:
c.shape

(3, 3)

In [6]:
a = np.random.randn(3, 4) # a.shape = (12288, 150)
b = np.random.randn(4, 1) 

c=a+b.T
c

array([[ 2.5805047 , -3.65284291, -0.19430223, -0.7049552 ],
       [-0.86621659, -1.94785545, -0.61135803,  1.67077496],
       [ 2.04822343, -0.97068084,  1.01878994,  1.55799778]])

In [7]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b) 
c.shape

(12288, 45)

In [25]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)c = a*b

a,b

(array([[ 0.2009659 ,  0.25996205, -1.05205818],
        [ 1.08097853,  1.41022259,  0.25990892],
        [ 1.27487302, -1.30309725, -0.45722812],
        [ 0.83849054,  0.56957859, -0.53241474]]),
 array([[-0.11755945, -0.15008187],
        [-0.08463991,  0.44634771],
        [ 0.90461564,  0.29407395]]))

In [26]:
c = a*b
c

ValueError: ignored

In [28]:
a=np.array([[1,2,3]])
b=np.array([[4],[5],[6]])
c=a*b
a.shape, b.shape, c.shape, c

((1, 3), (3, 1), (3, 3), array([[ 4,  8, 12],
        [ 5, 10, 15],
        [ 6, 12, 18]]))

In [29]:
c = np.dot(a,b)

c.shape, c

((1, 1), array([[32]]))

In [32]:
a=np.array([[1,2,3],
            [2,3,4],
            [3,4,5]])
b=np.array([[4],[5],[6]])
c=a*b

In [33]:
c

array([[ 4,  8, 12],
       [10, 15, 20],
       [18, 24, 30]])